apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-5gc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-5gc
  template:
    metadata:
      labels:
        app: open5gs-5gc
    spec:
      containers:
        - name: open5gs-5gc
          image: open5gs-5gc:latest
          command: ["5gc", "-c", "open5gs-5gc.yml"]
          ports:
            - containerPort: 9999
          env:
            - name: MONGODB_IP
              value: "127.0.0.1"
            - name: OPEN5GS_IP
              value: "10.53.1.2"
            - name: UE_IP_BASE
              value: "10.45.0"
            - name: UPF_ADVERTISE_IP
              value: "10.53.1.2"
            - name: DEBUG
              value: "false"
            - name: SUBSCRIBER_DB
              value: "001010123456780,00112233445566778899aabbccddeeff,opc,63bfa50ee6523365ff14c1f45f88737d,8000,9,10.45.1.2"
            - name: TZ
              value: "Europe/Madrid"
          securityContext:
            privileged: true
          livenessProbe:
            exec:
              command:
                - nc
                - -z
                - 127.0.0.20
                - "7777"
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 60
          # If you want to expose additional ports uncomment and add them here
          # ports:
          #   - containerPort: 38412
          #   - containerPort: 2152
